### ISSUE TITLE
Can not use placeholder in value under hasgreater

### ISSUE THREAD

**Issue by astirling** [rockyhawk64/CommandPanels#114]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
Yes

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
Yes

### Describe the bug
In a hasgreater block, when a placeholder is use for the value: key, the panel will err.  When placing the placeholder inside of quotes (single or double), there is no console error and the only thing shown in chat is "Error found in config at".  With debugging on this is shown in console: https://pastebin.com/UMuBYqqE

When using the placeholder and not using quote the following is shown in console: https://pastebin.com/twHhmfzU

### To Reproduce
1. Create a valid placeholder in the panel and give it a value
2. Use the placeholder in a hasgreaterblock as the value 
3. Reload CP
4. See error in console or Open Panel in game and see error in chat window

### Expected behavior
I expect the hasgreater block to evaluate the placeholder as an integer

### Screenshots/videos
If applicable, add screenshots or videos to help explain your problem.
N/A

### Versions:
 - Minecraft: [e.g. 1.16.5 paper]
 - CommandPanels: [e.g. 3.15.3.1]

### Additional context/Panel files
Add any other context or about the problem here. Please also send you're panel in question. We only accept [pastebin](https://pastebin.com/) links.
Panel is not complete (wanting to do more comparison so players don't get a lower boost than what is active.)
https://pastebin.com/hCMhQrFQ

**Comment by rockyhawk64** [comment]
**Using Quotes**
When placeholders are placed in the value: key without quotes that is expected to be an error and is not a bug, it is simply how YAML works.

**Features**
I am currently working on a new system for the placeholders as it will work better on the backend of the plugin. There are also a couple of features that were not supported that I will be adding in the next update such as setting panel data to the values of custom placeholders.
Placing placeholders in the `commands-on-open` area also will not work, as the panel opens before those commands are executed, so I will be adding `pre-load-commands` which will run the commands before the panel opens, that way you can use that instead for everything in your panel.

**Your Panel**
I have used your panel to test the development of the new features stated above but I have not used the entire panel, I have only used a portion of the panel (the first couple items) and edited it because there are quite a few errors, such as on line 67 you have double percentage signs `compare: '%%cp-boostcheck%%'` (there are other locations with similar issues).

**Comment by astirling** [comment]
Just for record, this is my final menu/panel that works as expected.
https://pastebin.com/JTXy0kbL
