### ISSUE TITLE
hasvalue greater than/less than, or equal to

### ISSUE THREAD

**Issue by Isaiah-labs** [rockyhawk64/CommandPanels#21]
**Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?**
Yes/**No**

**Have you checked the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) to see if your suggestion was already submitted and denied?**
**Yes**/No

**Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)?** *(Or got redirected to a Github issue here)*
**Yes**/No

**Is your feature request related to a problem? Please describe.**
There are no issues related to this feature request

**Describe the solution you'd like**
I'd like to see hasvalue have a <, <=, >, >= option, I'm trying to have an item display for a range of values, rather than just one.

**Describe alternatives you've considered**
Creating a separate item for each and every value I'd like, but I'm talking numbers into the thousands so it's just not practical.

**Additional context**

**Comment by fireFerry** [comment]
Rocky, the developer already told me he would be looking into this. He will later reply with new information.

**Comment by rockyhawk64** [comment]
This can be done using PlaceholderAPI, I have created an example item to explain.

You will need to use the JavaScript placeholder and hasvalue with CommandPanels combined. The example below will check to see if the placeholder "vault_eco_balance" which is the player's balance, is greater than 20 or not. If it is, it will return true, otherwise, it will return false.
This is why the `value: true` can be done, because it will not be comparing a number, but only a true/false value. If you need to reverse the outcome, you can always change value: to false, or even change output: to false (they'll do the same thing in this case).

```YAML
'23':
  material: REDSTONE_BLOCK
  name: 'You NEED $20!'
  lore:
  - '&cYou have $%vault_eco_balance%'
  hasvalue:
    output: true
    value: true
    compare: '%javascript_greater_than_{vault_eco_balance},20%'
    material: EMERALD_BLOCK
    name: 'You HAVE $20!'
```

To make this placeholder work, you will need to follow the javascript steps with PlaceholderAPI which is here:
https://github.com/PlaceholderAPI/Javascript-Expansion/wiki/Community-Scripts#how-to-use

When you get to the step that requires you to write javascript, I have done this for you, simply copy and paste this script I made into the `greater_than.js` file:
```JS
var placeholder;

function gThan() {
  if (args.length === 2) {
    placeholder = args[0];
  }else{
    return false;
  }
  if (placeholder > args[1]){
    return true;
  }else{
    return false;
  }
}

gThan();
```
