### ISSUE TITLE
Trojan was found in one of the plugin dependencies

### ISSUE THREAD

**Issue by CrazyCloudCraft** [rockyhawk64/CommandPanels#280]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

Purpur

#### The links could contain malware
</br>  
Java.Trojan.GenericGBA.31687 was found in the plugin CommandPanels with all versions above 3.18.3.0.

The reason is: The API from https://nexus.phoenixdevt.fr does this issue (That are the developers for MMOItems and so on) it probably contains this malware. However, the discord they provide isn't available, and their website does contain malware too.

### Steps to reproduce the issue

You need Bitdefender Plus in order to reproduce this.

### Expected behavior

Downloading the plugin without the Trojan from https://nexus.phoenixdevt.fr/repository/maven-public/

### After downloading your plugin
![1](https://github.com/rockyhawk64/CommandPanels/assets/95505222/903ba18a-16cb-4fe4-83ae-85520392bc6d)
### After building your plugin
![2](https://github.com/rockyhawk64/CommandPanels/assets/95505222/efa27028-9bd7-4c49-9703-78a36a63add8)
### Checking their website
![3](https://github.com/rockyhawk64/CommandPanels/assets/95505222/4e287677-ada4-4802-8971-1b2bedd3eb94)

**Comment by IceWolf23** [comment]
I just checked de latest version on VirusTotal, there is no virus on the plugin .jar i think

**Comment by rockyhawk64** [comment]
When using antivirus software on your Minecraft server folder, it's common to encounter false positives. This is often because many plugins, especially those from reputable sources like SpigotMC (as opposed to less trustworthy sites like BlackSpigot or cracked forums), need to access the internet for features like bStats, dependencies or version checking, which antivirus programs might mistakenly flag as suspicious. 
Although it's rare, there's a slight chance that jars could be infected with malware from external sources. However, it's not recommended to use standard antivirus software for scanning Minecraft plugin jars, as they are not typically effective in this context. Instead, to check the safety of Minecraft plugins, it's better to use specialised tools like the Spigot Anti-Malware, which you can find here: https://www.spigotmc.org/resources/spigot-anti-malware.64982/.

**Comment by CrazyCloudCraft** [comment]
I don't think that this is a false flag. However, it's not in the plugin code. Only in the dependencies. Virustotal doesn't show these, because it isn't a big problem. Bitdefender on the other side checks everything including the dependencies, which is smart for applications. But not for Minecraft plugins.

I will ignore the messages from Bitdefender for now on. 

(This is still an issue that should be fixed before spigotmc or someone else gets mad about that.)
