### ISSUE TITLE
Potential security issues with the /cpi command

### ISSUE THREAD

**Issue by Amgelo563** [rockyhawk64/CommandPanels#284]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if your suggestion is already added?
- [X] Have you checked the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your suggestion was already submitted and or denied?
- [X] Have you asked if the feature already exists in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)

### Is your feature request related to a problem? Please describe.

As a server owner, I'm worried about the potential exploits of the `/cpi` command. I really don't like a feature that directly downloads third party files, that an attacker could exploit if they somehow get access to the command.

Specifically, I listed these issues on the Discord server and got redirected here:
* Make the server try to fetch an infinite download or OOM the server with a big file.
* Use a path traversal exploit to save the yml file somewhere else (like other plugin's files).
* Load a menu that uses tags to execute commands in console, or other server threatening actions.
* Download a valid configuration file for another plugin, and use said plugin to execute unauthorized actions (like a Skript).

It's because of these that I consider that the command should be removed or at least tweaked to address those issues.

### Describe the solution you'd like

Some possible solutions I've came up with (there could be others, but ideally said solution should address the issues described above):

* Removing the command: This would be the most straightforward way, and I personally don't see any use case where a owner would need such a command. It rather seems like a niche feature that saves at most a few minutes but at the expense of potential security problems. It's worth noting that by searching `cpi` on the Discord server, there are only 5 mentions of it (the command), two of them being about security issues.
* Adding a toggle for it, turned off by default: By being turned off by default, at least server owners can know that they have such a feature in their server. Most owners don't really read the entire wiki, and could be surprised to find out that said feature even exists.

### Describe alternatives you've considered

The alternatives I've considered are listed on the solution proposals.

**Comment by TheLonelyWolf1** [comment]
Thank you for your feedback. I acknowledge your security concerns and admit that there may be opportunities to abuse this feature. 

However, since it is a help for some people when importing, a complete removal would be more of a negative turn.
Therefore, I think your second solution would make the most sense. I am currently discussing with the rest of the team how exactly the toggle can and should be implemented. 

As soon as I have a working implementation, I will add it to this repo via PR. 
I saidly can't give any ETA for when this toggle will be added to the live builds of CP as the lead developer is currently dealing with other things in RL.
