### ISSUE TITLE
Essentials Kit cooldown 

### ISSUE THREAD

**Issue by ImRealsy** [rockyhawk64/CommandPanels#57]
Hey, 

I was wondering if there was a way to change the panel display item once you select an essentials kit and show you how long is left on your kit cool down before you can open it again in the lore? 

Thankyou, the plugin is great!

**Comment by rockyhawk64** [comment]
https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#essentials
There are essentials placeholders you can use with PlaceholderAPI to show if kits are available, or for how long.

%essentials_kit_last_use_<kitname>%
%essentials_has_kit_<kitname>%
%essentials_kit_is_available_<kitname>%
%essentials_kit_time_until_available_<kitname>%

Just make sure you do 
/papi ecloud download Essentials
so that you have to placeholders installed.
