### ISSUE TITLE
Command panels with multiple inventories

### ISSUE THREAD

**Issue by mani00132** [rockyhawk64/CommandPanels#68]
I have the problem that i have the plugin PerWorldInventory, and so I want every player to always have the compass with which you can open a navigation command panel, but everything else should change if you change worlds, but that only works in the world where you spawn, if you then change worlds, you won't have the compass in your inventory

**Comment by fireFerry** [comment]
Hello, you've not used the template we created, please do so we don't have to ask questions you can already answer in the template. Command Panels should give the item in every world you have permission for.

**Comment by mani00132** [comment]
so I added all permissions of the wiki for all players and it is still not working...

**Comment by rockyhawk64** [comment]
The plugin will always give the players the compass in every world, you will need to add to the list of the disabled worlds within the command panel in order to stop the item from spawning in a specific world.

Once that is done, the compass will still be in the disabled world, but it will no longer work. Simply throwing out the old compass will remove it, and it will never spawn back again.
