### ISSUE TITLE
Could not pass event InventoryClickEvent to CommandPanels

### ISSUE THREAD

**Issue by Chillchillnetwork** [rockyhawk64/CommandPanels#86]
### Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
Yes

### Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
Yes

### Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? *(Or got redirected to a Github issue here)*
No

### Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?
No

### Describe the bug
Could not pass event InventoryClickEvent to CommandPanels

### Versions:
 - Minecraft: 1.16.4
 - CommandPanels: 3.14.2.1

### Additional context/Panel files
https://mcpaste.io/c70b6aa888abf0da

**Comment by rockyhawk64** [comment]
It appears like you are executing the command using the `console=` tag. I cannot test this for myself so I had to analyze the error, but it appears like it is CMI that is causing the issue, not CommandPanels.
`Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player`
It states here that the command `/cmi` cannot be used in the console, and sends the error.
